apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxdeploy
  template:
    metadata:
      labels:
        app: nginxdeploy

    spec:
      containers:
      - name: nginxdeploy
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
